#!/bin/sh

VERS=$(nvram get webs_state_info)

. /jffs/scripts/credentials.sh

push_message () {
	echo "starting push"
	curl -s \
		 --form-string "token=$pushover_token" \
		 --form-string "user=$pushover_user" \
		 --form-string "message=Just letting my self know that your router needs to be updated to version $VERS" \
		https://api.pushover.net/1/messages.json
}
push_message
