#!/bin/sh

. /jffs/scripts/credentials.sh

push_message(){
    echo "starting push"
    curl -s \
          --form-string "token=$pushover_token"\
          --form-string "user=$pushover_user"\
          --form-string "message=Home just connected to the internet"\
          https://api.pushover.net/1/messages.json
}

if [ "$2" = "connected" ]; then
   push_message
fi
